[package]

name = "statrs"
version = "0.13.0"
authors = ["Michael Ma"]
description = "Statistical computing library for Rust"
license = "MIT"
keywords = ["probability", "statistics", "stats", "distribution", "math"]
categories = ["science"]
documentation = "https://docs.rs/statrs/0.13.0/statrs/"
homepage = "https://github.com/boxtown/statrs"
repository = "https://github.com/boxtown/statrs"
edition = "2018"

[lib]

name = "statrs"
path = "src/lib.rs"

[dependencies]
rand = "0.8.3"
nalgebra = { version="0.25.4",  default-features=true, features=["rand"] }
approx = "0.4.0"
num-traits = "0.2.14"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "order_statistics"
harness = false
